### ISSUE TITLE
cell ID corresponding patient ID

### ISSUE THREAD

**Issue by LuShuYangMing** [GregorySchwartz/multiomics-single-cell-t1d#10]
Hi Gregory:
I have a small question, where can we get the information of cell from which patient? For example, I processed the file from [cellxgene](https://cellxgene.cziscience.com/e/37b21763-7f0f-41ae-9001-60bad6e2841d.cxg/), and get the cell ID like this "AAACCTGAGGTGTGGT-1" "AAACCTGCACGCCAGT-1" "AAACCTGCAGTCGATT-1". Although the information of patients was provided in the supplementary table 1, we can not find the AAACCTGCACGCCAGT-1 from which patient. Besides, we also downloaded the h5 files from NCBI, unfortunately, we still can not find this relationship. So would you like to help us to get **CellID-to-Patient relationship** table?

Thank you very much!

**Comment by GregorySchwartz** [comment]
Should be solved in https://github.com/GregorySchwartz/multiomics-single-cell-t1d/pull/11.
